SPOTIPY_CLIENT_ID="f2560d6cbcfd4eab90ec2a026b0aecf7"
SPOTIPY_CLIENT_SECRET="0340e484db5a492fa53a56b13ce92cd7"
MAPBOX_TOKEN = "pk.eyJ1IjoibWFjaW9rb29vIiwiYSI6ImNtanNmOWw5NzRjMmMzY3F6cm81dXlyMGgifQ.ge0Pu3M96VEw8qosWBKrBA"
GENIUS_ACCESS_TOKEN = "3O6Gergq8PJj06gtdB2sfrFwPdEMCgZzaN1rdjumu8Bwu8GVHZsYYgMzBsxUAxeF"